---
language: python
python: "3.8"

# Use the new container infrastructure
sudo: true

services:
  - docker

env:
  - MOLECULE_NO_LOG="false"

install:
  - pip3 install ansible ansible-lint docker 'molecule[docker]' docker-py

script:
  - travis_wait 60 molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
