---
language: python
python: "3.6"

# Use the new container infrastructure
sudo: true

services:
  - docker

env:
  - MOLECULE_NO_LOG="false"

install:
  - pip install ansible>=2.4.3.0
  - pip install ansible-lint>=3.4.20
  - pip install docker
  - pip install molecule>=2.17.0
  - pip install docker-py

script:
  - travis_wait 60 molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
