#
# Configure Tomcat
#

- name: generate a custom "setenv.sh" from template, provides the ability to configure Tomcat at start-up from outside the container
  template:
    src: setenv.sh.j2
    dest: "{{ tomcat_catalina_base }}/bin/setenv.sh"
    mode: ug+x

- name: generate a custom "jmxremote.password" from template, to use pasword protected JMX ports
  template:
    src: jmxremote.password.j2
    dest: "{{ tomcat_catalina_base }}/comf/jmxremote.password"
    mode: 0600

- name: generate a custom "jmxremote.access" from template, to use pasword protected JMX ports
  template:
    src: jmxremote.access.j2
    dest: "{{ tomcat_catalina_base }}/comf/jmxremote.access"
    mode: 0600
