---
#
# Configure Tomcat
#

- name: generate a custom 'setenv.sh' from template, provides the ability to configure Tomcat at start-up from outside the container
  template:
    src: setenv.sh.j2
    dest: "{{ tomcat_system_home }}{{ item.instance_name }}/bin/setenv.sh"
    mode: ug+x
  with_items: {{ tomcat_instance }}

- name: "generate a custom '.jmxremote.password' from template, to use pasword protected JMX ports"
  template:
    src: jmxremote.password.j2
    dest: "{{ tomcat_system_home }}{{ item.instance_name }}/conf/{{ item.instance_name }}.jmxremote.password"
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: 0600
  with_items: {{ tomcat_instance}}

- name: "generate a custom 'jmxremote.access' from template, to use pasword protected JMX ports"
  template:
    src: jmxremote.access.j2
    dest: "{{ tomcat_system_home }}{{ item.instance_name }}/conf/{{ item.instance_name }}.jmxremote.access"
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: 0640
  with_items: {{ tomcat_instance}}

- name: generate Tomcat init script
  template:
    src: tomcat.j2
    dest: "/etc/init.d/{{ item.instance_name }}"
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: 0750
  with_items: {{ tomcat_instance}}

- name: "Prepare daily catalina.out logrotate"
  template:
    dest: '/etc/logrotate.d/{{ tomcat_system_name }}-catalina'
    src: "logrotate-catalina-out.j2"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Check cron.d folder"
  stat:
    path: /etc/cron.d
  register: cron_d_dir

- name: "Prepare daily log, txt, current logrotate cron.d task"
  template:
    dest: '/etc/cron.d/{{ tomcat_system_name }}-logs'
    src: "tomcat-logs.j2"
    owner: "root"
    group: "root"
    mode: "0644"
  when: cron_d_dir.stat.exists
