#
# Configure Tomcat
#

- name: generate a custom 'setenv.sh' from template, provides the ability to configure Tomcat at start-up from outside the container
  template:
    src: setenv.sh.j2
    dest: "{{ tomcat_catalina_base }}/bin/setenv.sh"
    mode: ug+x

- name: "generate a custom '{{ tomcat_process_name }}.jmxremote.password' from template, to use pasword protected JMX ports"
  template:
    src: jmxremote.password.j2
    dest: "{{ tomcat_catalina_base }}/conf/{{ tomcat_process_name }}.jmxremote.password"
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: 0600

- name: "generate a custom '{{ tomcat_process_name }}.jmxremote.access' from template, to use pasword protected JMX ports"
  template:
    src: jmxremote.access.j2
    dest: "{{ tomcat_catalina_base }}/conf/{{ tomcat_process_name }}.jmxremote.access"
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: 0640

- name: add {{ tomcat_page_encoding }} encoding to the server connector
  xml:
    file: "{{ tomcat_catalina_home }}/conf/server.xml"
    xpath: "/Server/Service/Connector"
    attribute: "URIEncoding"
    ensure: present
    value: '{{ tomcat_page_encoding }}'

- name: add digest encoding to the server connector
  xml:
    file: "{{ tomcat_catalina_home }}/conf/server.xml"
    xpath: "/Server/Service/Engine/Realm"
    attribute: "digest"
    ensure: present
    value: "sha-512"
  when: tomcat_manager_hash_password != false

- name: generate Tomcat init script
  template:
    src: tomcat.j2
    dest: "/etc/init.d/{{ tomcat_process_name }}"
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: 0750
