#
# Custom Error Pages
#

- name: error pages | create errorpages directory
  file:
    path: "{{ tomcat_catalina_home }}/webapps/ROOT/errorpages/"
    state: directory
    owner: "{{ tomcat_root_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rx,o="

- name: error pages | download custom erropages for Tomcat
  get_url:
    url: "{{ tomcat_custom_errorpages_url }}/{{ item }}.html"
    dest: "{{ tomcat_catalina_home }}/webapps/ROOT/errorpages/{{ item }}.jsp"
  with_items:
  - "{{ tomcat_errorpages }}"

- name: "generate a custom 'web_error_pages.xml' from template"
  template:
    src: web_error_pages.xml.j2
    dest: "{{ tomcat_catalina_base }}/conf/web_error_pages.xml"
    owner: "{{ tomcat_root_user }}"
    group: "{{ tomcat_system_group }}"
    mode: 0640
