#
# Hardening Tomcat
#

- name: hardening | add empty Server response header
  xml:
    file: "{{ tomcat_catalina_base }}/conf/server.xml"
    xpath: "/Server/Service/Connector"
    attribute: "Server"
    ensure: present
    value: " "

- name: hardening | add Secure flag to response header
  xml:
    file: "{{ tomcat_catalina_base }}/conf/server.xml"
    xpath: "/Server/Service/Connector"
    attribute: "Secure"
    ensure: present
    value: "true"

- name: hardening | set Tomcat's shutdown port
  xml:
    file: "{{ tomcat_catalina_base }}/conf/server.xml"
    xpath: "/Server"
    attribute: "port"
    ensure: present
    value: "{{ tomcat_shutdown_port }}"

- name: hardening | set Tomcat's shutdown command
  xml:
    file: "{{ tomcat_catalina_base }}/conf/server.xml"
    xpath: "/Server"
    attribute: "command"
    ensure: present
    value: "{{ tomcat_shutdown_command }}"

- name: hardening | add usehttponly for contexes
  xml:
    file: "{{ tomcat_catalina_base }}/conf/context.xml"
    xpath: "/Context"
    attribute: "useHttpOnly"
    ensure: present
    value: "true"

- name: disable unnecessary default applications
  command: "mv {{ tomcat_catalina_base }}/webapps/docs {{ tomcat_catalina_base }}/webapps-disabled/docs "
    creates: "path/to/bar" mv /path/to/foo /path/to/bar

I used to do a 2 task approach using stat like Bruce P suggests. Now I do this as one task with creates. I think this is a lot clearer.
share
    
answered Jun 27 '14 at 17:42
Tom Ekberg
1,36786
    
36 	 
    
Or, even better: command:  creates: {{ tomcat_catalina_base }}/webapps-disabled/docs removes:/path/to/foo – Fonant Apr 7 '15 at 15:49 