#
# Hardening Tomcat
#

- name: hardening | add empty Server response header
  xml:
    file: "{{ tomcat_catalina_home }}/conf/server.xml"
    xpath: "/Server/Service/Connector"
    attribute: "Server"
    ensure: present
    value: " "

- name: hardening | set Secure flag to True in response header
  xml:
    file: "{{ tomcat_catalina_home }}/conf/server.xml"
    xpath: "/Server/Service/Connector"
    attribute: "Secure"
    ensure: present
    value: "true"
  when: tomcat_use_secure_flag == True

- name: hardening | set Secure flag to Flase in response header
  xml:
    file: "{{ tomcat_catalina_home }}/conf/server.xml"
    xpath: "/Server/Service/Connector"
    attribute: "Secure"
    ensure: present
    value: "false"
  when: tomcat_use_secure_flag != True

- name: hardening | set Tomcat's shutdown port
  xml:
    file: "{{ tomcat_catalina_home }}/conf/server.xml"
    xpath: "/Server"
    attribute: "port"
    ensure: present
    value: "{{ tomcat_shutdown_port }}"

- name: hardening | set Tomcat's shutdown command
  xml:
    file: "{{ tomcat_catalina_home }}/conf/server.xml"
    xpath: "/Server"
    attribute: "command"
    ensure: present
    value: "{{ tomcat_shutdown_command }}"

- name: hardening | add usehttponly for contexes
  xml:
    file: "{{ tomcat_catalina_home }}/conf/context.xml"
    xpath: "/Context"
    attribute: "useHttpOnly"
    ensure: present
    value: "true"

- name: 'hardening | add session timeout: {{ tomcat_session_timeout }}'
  xml:
    file: "{{ tomcat_catalina_home }}/conf/web.xml"
    namespaces:
      javaee: http://java.sun.com/xml/ns/javaee
    xpath:  "/javaee:web-app/session-config"
    add_children:
     - session-timeout: "{{ tomcat_session_timeout }}"

- name: hardening | set session http-only flag to True
  xml:
    file: "{{ tomcat_catalina_home }}/conf/web.xml"
    namespaces:
      javaee: http://java.sun.com/xml/ns/javaee
    xpath:  "/javaee:web-app/session-config"
    add_children:
     - http-only: "true"
  when: tomcat_session_http_only == True

- name: hardening | set session http-only flag to False
  xml:
    file: "{{ tomcat_catalina_home }}/conf/web.xml"
    namespaces:
      javaee: http://java.sun.com/xml/ns/javaee
    xpath:  "/javaee:web-app/session-config/http-only"
    add_children:
     - http-only: "false"
  when: tomcat_session_http_only != True

- name: hardening | set session http-only flag to True
  xml:
    file: "{{ tomcat_catalina_home }}/conf/web.xml"
    namespaces:
      javaee: http://java.sun.com/xml/ns/javaee
    xpath:  "/javaee:web-app/session-config"
    add_children:
     - secure: "true"
  when: tomcat_session_secure == True

- name: hardening | set session http-only flag to False
  xml:
    file: "{{ tomcat_catalina_home }}/conf/web.xml"
    namespaces:
      javaee: http://java.sun.com/xml/ns/javaee
    xpath:  "/javaee:web-app/session-config"
    add_children:
     - secure: "false"
  when: tomcat_session_secure != True

- name: disable unnecessary default applications
  command: "mv {{ tomcat_catalina_home }}/webapps/{{ item }} {{ tomcat_catalina_home }}/webapps-disabled/{{ item }}"
  args:
    creates: "{{ tomcat_catalina_home }}/webapps-disabled/{{ item }}"
    removes: "{{ tomcat_catalina_home }}/webapps/{{ item }}"
  with_items:
  - "docs"
  - "examples"
