---
#
# Hardening Tomcat
#

- name: copy recommended default applications
  command: "cp -r --preserve=mode,ownership,timestamps {{ tomcat_catalina_home }}/webapps/{{ item.0 }} {{ tomcat_system_home }}{{ item.1.instance_name }}/webapps/{{ item.0 }}"
  args:
    creates: "{{ tomcat_system_home }}{{ item.1.instance_name }}/webapps/{{ item.0 }}/"
  with_nested:
    - "{{ tomcat_copy_webapps }}"
    - "{{ tomcat_instance }}"

- name: generate manager context file
  template:
    src: manager-context.xml.j2
    dest: "{{ tomcat_system_home }}{{ item.instance_name }}/webapps/manager/META-INF/context.xml"
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: 0640
  with_items: "{{ tomcat_instance }}"
