#
# Installs Tomcat, following best practices of separating CATALINA_BASE directory from CATALINA_HOME
#
---
- name: install Tomcat
  include: install-tomcat.yml

#- name: remove bat files on non-Windows systems
#  include: removebat-nonwindows.yml
#  static: no
#  when: "ansible_os_family != 'Windows'"

- name: prepare Catalina base
  include: prepare-catalina-base.yml

- { include: xmlx-package-Debian.yml, when: "ansible_os_family == 'Debian'", static: no }
- { include: xmlx-package-RedHat.yml, when: "ansible_os_family == 'RedHat'", static: no }

- name: configure Tomcat for customisation on start-up
  include: configure-tomcat.yml

- name: hardening Tomcat
  include: hardening-tomcat.yml

- name: add custom error pages
  include: custom-errorpages-tomcat.yml
  when: tomcat_use_custom_error_pages

- name: enable logstash
  include: enable-logstash.yml
  when: tomcat_enable_logstash
