---
#
# Configure Tomcat firewalld
#

- name: install firewalld package
  package:
    name: firewalld
    state: present

- name: ensure firewalld is running and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: true

- name: 'configure firewalld for http port'
  firewalld:
    port: '{{ item.0.http_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.0.http_zone }}'
    source: '{{ item.1 }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - http_source

- name: 'configure firewalld for ajb port'
  firewalld:
    port: '{{ item.0.ajb_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.0.ajb_zone }}'
    source: '{{ item.1 }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - ajb_source

- name: 'configure firewalld for https port'
  firewalld:
    port: '{{ item.0.https_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.0.https_zone }}'
    source: '{{ item.1 }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - https_source

- name: 'configure firewalld for jmx port {{ tomcat_jmx_port }}'
  firewalld:
    port: '{{ tomcat_jmx_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ tomcat_jmx_zone }}'
  with_items:
    - '{{ tomcat_jmx_source }}'

- name: 'configure firewalld for shutdown port {{ tomcat_shutdown_port }}'
  firewalld:
    port: '{{ tomcat_shutdown_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ tomcat_shutdown_zone }}'
  with_items:
    - '{{ tomcat_https_source }}'
