---
#
# Configure Tomcat firewalld
#

- name: install firewalld package
  package:
    name: firewalld
    state: present

- name: ensure firewalld is running and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: true

- name: 'configure firewalld for http port'
  firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ item.1 }}" port port={{ item.0.http_port }} protocol=tcp accept'
    permanent: true
    immediate: true
    state: enabled
  with_subelements:
    - '{{ tomcat_instance }}'
    - http_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for ajp port'
  firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ item.1 }}" port port={{ item.0.ajp_port }} protocol=tcp accept'
    permanent: true
    immediate: true
    state: enabled
  with_subelements:
    - '{{ tomcat_instance }}'
    - ajp_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for https port'
  firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ item.1 }}" port port={{ item.0.https_port }} protocol=tcp accept'
    permanent: true
    immediate: true
    state: enabled
  with_subelements:
    - '{{ tomcat_instance }}'
    - https_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for jmx port'
  firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ item.1 }}" port port={{ item.0.jmx_port }} protocol=tcp accept'
    permanent: true
    immediate: true
    state: enabled
  with_subelements:
    - '{{ tomcat_instance }}'
    - jmx_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for shutdown port'
  firewalld:
    rich_rule: 'rule family=ipv4 source address="{{ item.1 }}" port port={{ item.0.shutdown_port }} protocol=tcp accept'
    permanent: true
    immediate: true
    state: enabled
  with_subelements:
    - '{{ tomcat_instance }}'
    - https_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for http port'
  firewalld:
    port: '{{ item.http_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.http_zone }}'
  with_items:
    - '{{ tomcat_instance }}'
  when: tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for ajp port'
  firewalld:
    port: '{{ item.ajp_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.ajp_zone }}'
  with_items:
    - '{{ tomcat_instance }}'
  when: tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for https port'
  firewalld:
    port: '{{ item.https_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.https_zone }}'
  with_items:
    - '{{ tomcat_instance }}'
  when: tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for jmx port'
  firewalld:
    port: '{{ item.jmx_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.jmx_zone }}'
  with_items:
    - '{{ tomcat_instance }}'
  when: tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for shutdown port'
  firewalld:
    port: '{{ item.shutdown_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.shutdown_zone }}'
  with_items:
    - '{{ tomcat_instance }}'
  when: tomcat_manage_firewalld_use_zone
