---
#
# Configure Tomcat firewalld
#

- name: install firewalld package
  package:
    name: firewalld
    state: present

- name: ensure firewalld is running and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: true

- name: 'configure firewalld for http port'
  firewalld:
    port: '{{ item.0.http_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    source: '{{ item.1 }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - http_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for ajb port'
  firewalld:
    port: '{{ item.0.ajb_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    source: '{{ item.1 }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - ajb_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for https port'
  firewalld:
    port: '{{ item.0.https_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    source: '{{ item.1 }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - https_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for jmx port'
  firewalld:
    port: '{{ item.0.jmx_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    source: '{{ item.1 }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - jmx_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for shutdown port'
  firewalld:
    port: '{{ item.0.shutdown_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    source: '{{ item.1 }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - https_source
  when: not tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for http port'
  firewalld:
    port: '{{ item.0.http_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.0.http_zone }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - http_source
  when: tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for ajb port'
  firewalld:
    port: '{{ item.0.ajb_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.0.ajb_zone }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - ajb_source
  when: tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for https port'
  firewalld:
    port: '{{ item.0.https_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.0.https_zone }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - https_source
  when: tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for jmx port'
  firewalld:
    port: '{{ item.0.jmx_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.0.jmx_zone }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - jmx_source
  when: tomcat_manage_firewalld_use_zone

- name: 'configure firewalld for shutdown port'
  firewalld:
    port: '{{ item.0.shutdown_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
    zone: '{{ item.0.shutdown_zone }}'
  with_subelements:
    - '{{ tomcat_instance }}'
    - https_source
  when: tomcat_manage_firewalld_use_zone
