---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
    - name: tomcat-centos6-10-jdk
      image: kami911/docker-centos6-ansible
      image_version: latest
      groups:
        - jdk
        - centos6

    - name: tomcat-centos6-10-server-jre
      image: kami911/docker-centos6-ansible
      image_version: latest
      groups:
        - server-jre
        - centos6
  
    - name: tomcat-centos7-10-jdk
      image: milcom/centos7-systemd
      privileged: true
      groups:
        - jdk
        - centos7

    - name: tomcat-centos7-10-server-jre
      image: milcom/centos7-systemd
      image_version: latest
      privileged: true
      groups:
        - server-jre
        - centos7

  #- name: tomcat-centos7-10-jdk-firewalld-source
  #  image: milcom/centos7-systemd
  #  image_version: latest
  #  privileged: true
  #  groups:
  #    - jdk
  #    - centos7
  #    - firewalld_source

  #- name: tomcat-centos7-10-server-jre-firewalld-source
  #  image: milcom/centos7-systemd
  #  image_version: latest
  #  privileged: true
  #  groups:
  #    - server-jre
  #    - centos7
  #    - firewalld_source

    - name: java-centos8-11-jdk
      image: geerlingguy/docker-centos8-ansible
      image_version: latest
      privileged: true
      groups:
        - jdk
        - python3
        - centos8

    - name: java-centos8-11-server-jre
      image: geerlingguy/docker-centos8-ansible
      image_version: latest
      privileged: true
      groups:
        - server-jre
        - python3
        - centos8

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      jdk:
        java_type: 'jdk'
      server-jre:
        java_type: 'serverjre'
      ubuntu14:
        tomcat_manage_firewalld: false
      ubuntu16:
        tomcat_manage_firewalld: false
      ubuntu18:
        tomcat_manage_firewalld: false
      centos6:
        tomcat_manage_firewalld: false
      centos7:
        tomcat_manage_firewalld: true
      centos8:
        tomcat_manage_firewalld: true
      firewalld_source:
        tomcat_manage_firewalld_use_zone: false
      ubuntu:
        tomcat_manage_firewalld: false
      python3:
        ansible_python_interpreter: '/usr/bin/env python3'
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
